In [2]:
import numpy as np

In [9]:
A = np.array([1,2,3])
print(A)
print(A.ndim)
print(60*"_")
B = np.array([[2,3,4,5,5],[5,6,3,3,1],[2,2,3,1,0]])

print(B)
print(B.ndim)
print(B.shape)
print(B.dtype)

print("first row",B[0,:])
print("second row",B[1,2:])

[1 2 3]
1
____________________________________________________________
[[2 3 4 5 5]
 [5 6 3 3 1]
 [2 2 3 1 0]]
2
(3, 5)
int32
first row [2 3 4 5 5]
second row [3 3 1]


In [14]:
S = np.zeros((2,3))
print("S","\n",S)

D = np.ones((2,3))
print("D","\n",D)

F = np.full((2,3),7)
print("F","\n",F)

G = np.identity(3)
print("G","\n",G)

R = np.random.rand(2,3)
print("R","\n",R)

S 
 [[0. 0. 0.]
 [0. 0. 0.]]
D 
 [[1. 1. 1.]
 [1. 1. 1.]]
F 
 [[7 7 7]
 [7 7 7]]
G 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
R 
 [[0.86117401 0.33389347 0.83464272]
 [0.81214895 0.11616023 0.95158193]]



Copy

In [3]:
X = np.array([[1,2,3],[4,5,6]])
print(X,"\n")

Y = X.copy()
Y[1,2]=9
print(Y)

[[1 2 3]
 [4 5 6]] 

[[1 2 3]
 [4 5 9]]


Arathmatic Operation

In [5]:
arr = np.array([[1,2,3],[4,5,6]]) 
print("+","\n",arr+1,"\n")
print("-","\n",arr-1,"\n")
print("*","\n",arr*2,"\n")
print("/","\n",arr/2,"\n")

+ 
 [[2 3 4]
 [5 6 7]] 

- 
 [[0 1 2]
 [3 4 5]] 

* 
 [[ 2  4  6]
 [ 8 10 12]] 

/ 
 [[0.5 1.  1.5]
 [2.  2.5 3. ]] 



Repeating

In [7]:
arr = np.array([[1,2,3],[4,5,6]]) 
print("Array","\n",arr,"\n")

arr1 = np.repeat(arr,2)
print("Array1","\n",arr1,"\n")

arr2 = np.repeat(arr,2,axis=0)
print("Array2","\n",arr2,"\n")


arr3 = np.repeat(arr,2,axis=1)
print("Array3","\n",arr3,"\n")



Array 
 [[1 2 3]
 [4 5 6]] 

Array1 
 [1 1 2 2 3 3 4 4 5 5 6 6] 

Array2 
 [[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]] 

Array3 
 [[1 1 2 2 3 3]
 [4 4 5 5 6 6]] 



In [9]:
a = np.array([2,4,6])
print(a)
b = np.array([3,5,7])
print("\n",b,"\n")
print("Vertical","\n",np.vstack([b,a,a,b]))


[2 4 6]

 [3 5 7] 

Vertical 
 [[3 5 7]
 [2 4 6]
 [2 4 6]
 [3 5 7]]


Concatnation

In [17]:
h1 = np.array([[2,3,3,1],[0,0,0,0]])
h2 = np.array([[1,1,1,1],[7,7,7,7]])
print(np.concatenate((h1,h2), axis=0))
print(50*"=")
print(np.concatenate((h1,h2), axis=1))
print(50*"=")
print(np.vstack((h1,h2)))
print(50*"=")
print(np.hstack((h1,h2)))

[[2 3 3 1]
 [0 0 0 0]
 [1 1 1 1]
 [7 7 7 7]]
[[2 3 3 1 1 1 1 1]
 [0 0 0 0 7 7 7 7]]
[[2 3 3 1]
 [0 0 0 0]
 [1 1 1 1]
 [7 7 7 7]]
[[2 3 3 1 1 1 1 1]
 [0 0 0 0 7 7 7 7]]


In [ ]:
arry = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print("Array \n",arry)
print(arry.reshape(5,2))
print(40*"=")
print(np.transpose(arry))
print(40*"=")
print()

Array 
 [[1 2 3 4 5]
 [6 7 8 9 0]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 0]]
[[1 6]
 [2 7]
 [3 8]
 [4 9]
 [5 0]]


In [15]:
T = np.array([[1,2,3],[4,5,6]])
print("T \n",T,"\n")

T1 = np.append(T,[[0,0,0]],axis=0)
print("T1 \n",T1,"\n")

T3 = np.insert(T,2,[[6,6,6]],axis=0)
print("T3 \n",T3,"\n")

T4 = np.insert(T,2,[0,0],axis=1)
print("T4 \n",T4,"\n")

T5 = np.delete(T,2,axis=1)
print("T5 \n",T5,"\n")





T 
 [[1 2 3]
 [4 5 6]] 

T1 
 [[1 2 3]
 [4 5 6]
 [0 0 0]] 

T3 
 [[1 2 3]
 [4 5 6]
 [6 6 6]] 

T4 
 [[1 2 0 3]
 [4 5 0 6]] 

T5 
 [[1 2]
 [4 5]] 



In [18]:
S = np.array([[1,2,3,1],[4,5,6,4],[7,8,9,7],[1,1,1,1]])
print("S \n",S,"\n")
D = S[1:3,2:]
print("D \n",D)


S 
 [[1 2 3 1]
 [4 5 6 4]
 [7 8 9 7]
 [1 1 1 1]] 

D 
 [[6 4]
 [9 7]]
